---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-v1
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app

    containers:
      - image:
