apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    kind: CronTab
    listKind: CronTabList
    plural: crontabs
    singular: crontab
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                field:
                  type: string
                status:
                  type: string
  scope: Namespaced
  names:
    kind: CronTab
    listKind: CronTabList
    plural: crontabs
    singular: crontab
    shortNames:
      - ct
      - crontab
      - crontabs
