apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: connectivity-test

spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx
  type: ClusterIP
