apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: connectivity-test
  labels:
    app: debug

spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1024Mi
