---
apiVersion: v1
kind: Pod
metadata:
  name: net-client
  labels:
    app: net-client
spec:
  containers:
    - name: net-client
      image: busybox
      # This pod sleeps so you can exec into it for connectivity testing
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
